export const clients = [
    {
        id:1,
        name:'Carlos',
        lastName:'Galindo',
        age:19
    },
    {
        id:2,
        name:'Erasmo',
        lastName:'Diaz',
        age:20
    },
    {
        id:3,
        name:'Sofia',
        lastName:'Campos',
        age:24
    },
    {
        id:4,
        name:'Eduardo',
        lastName:'Corpus',
        age:27
    },
    {
        id:5,
        name:'Lorena',
        lastName:'Ortiz',
        age:26
    },
    {
        id:6,
        name:'Jacob',
        lastName:'Escareño',
        age:19
    }
];
